name: Test TYPO3 Extension

on: [ push, pull_request ]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: TYPO3 ${{ matrix.typo3}} tests on PHP ${{ matrix.php }}

    strategy:
      fail-fast: false
      matrix:
        php: [ 7.4, 8.1 ]
        typo3: [ 11.5 ]

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: 'xdebug3'
          extensions: pdo, sqlite3

      - name: 'Get Composer Cache Directory'
        id: composer-cache
        shell: bash
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: 'Cache Composer Dependencies'
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-php${{ matrix.php }}-typo3${{ matrix.typo3 }}

      - name: 'Validate composer.json and composer.lock'
        shell: bash
        run: composer validate --strict

      - name: 'Install TYPO3 core'
        shell: bash
        run: composer require typo3/cms-core="^${{ matrix.typo3 }}" -W

      - name: 'PHPUnit unit tests'
        shell: bash
        run: composer test-unit

      - name: 'PHPUnit functional tests'
        shell: bash
        run: composer test-functional

      # merge result files from unit tests and functional tests
      - name: 'Merge Coverage Reports'
        shell: bash
        run: .Build/bin/phpcov merge --php .Build/logs/coverage.php --html .Build/logs/coverage/merged --cobertura .Build/logs/cobertura.xml .Build/logs/coverage/

      # finally use the cobertura report and generate coverage summary
      - name: 'Code Coverage Summary Report'
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: .Build/logs/cobertura.xml
          badge: true
          # there are not enough tests yet
          fail_below_min: false
          format: markdown
          hide_branch_rate: true
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
